/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtDots: typeof import('./src/components/ArtDots.vue')['default']
    ArtPlum: typeof import('./src/components/ArtPlum.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    LogoStroke: typeof import('./src/components/LogoStroke.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RobertLewis: typeof import('./src/components/icons/RobertLewis.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slidev: typeof import('./src/components/icons/Slidev.vue')['default']
    TextCopy: typeof import('./src/components/TextCopy.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WrapperDemo: typeof import('./src/components/WrapperDemo.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
